query GetChurches {
  getChurchs {
    data {
      countryId
      id
      logo
      name
      verified
      address {
        street
      }
    }
    pagination {
      currentPage
      limit
      totalCount
      totalPage
    }
  }
}
